<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Active' => 'Активный',
  'Activate' => 'Активировать',
  'Advanced Search' => 'Расширенный поиск',
  'Any' => 'Произвольный',
  'Are you sure you want to delete this user?' => 'Вы уверены в том что хотите удалить данного пользователя?',
  'Create' => 'Создать',
  'Create user' => 'Создать пользователя',
  'Created On' => 'Дата создания',
  'Deactivate' => 'Деактивировать',
  'Delete user {id}' => 'Удалить пользователя {id}',
  'Disable' => 'Заблокировать',
  'Disabled' => 'Заблокирован',
  'Enable' => 'Разблокировать',
  'Enabled' => 'Разблокирован',
  'Email' => 'Email',
  'Email Verified' => 'Email подтвержден',
  'Email Verified short' => 'Email подтв.',
  'Fields with {asterisk} are required.' => 'Поля со {asterisk} обязательны.',
  'Firstname' => 'Имя',
  'Is Active' => 'Активный',
  'Is Active short' => 'Актив.',
  'Is Disabled' => 'Заблокирован',
  'Is Disabled short' => 'Забл.',
  'Last Visit On' => 'Последний раз входил',
  'Last Visit On short' => 'Посл. раз входил',
  'Lastname' => 'Фамилия',
  'List users' => 'Перечень пользователей',
  'No' => 'Нет',
  'Not active' => 'Неактивен',
  'Password Set On' => 'Пароль задан',
  'Save' => 'Сохранить',
  'Search' => 'Поиск',
  'Unverified' => 'Не проверен',
  'Unverify' => 'Снять подтверждение',
  'Update' => 'Обновить',
  'Update user {id}' => 'Обновить пользователя {id}',
  'Updated On' => 'Обновлен',
  'Users manager' => 'Управление пользователями',
  'Username' => 'Имя пользователя',
  'Username short' => 'Логин',
  'Verify' => 'Подтвердить',
  'Verified' => 'Подтвержден',
  'View user {id}' => 'Просмотреть данный о пользователе {id}',
  'Yes' => 'Да',
  'You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b> or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.' => 'Можно использовать следующие операторы сравнения (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b> или <b>=</b>).',
);
